### ISSUE TITLE
Myriad 'Positives' from virustotal.com

### ISSUE THREAD

**Issue by Hunanbean-Collective** [DannyBen/TinySpeech#1]
Any way you can eliminate these?
![image](https://github.com/DannyBen/TinySpeech/assets/71809825/5304638d-d4f1-43ae-9bc9-6d2c7c841069)

**Comment by DannyBen** [comment]
Not sure which file you checked. I am getting less (9/74) than what your screenshot shows.
https://www.virustotal.com/gui/file/af8d0d5c30cc8f683d4a286d5bfeb2b3edb70937f3739885c0048c01a63d2dd5?nocache=1

Can you add the URL to the virustotal page?

Not much I can do about it - AutoIT / AutoHotkey binaries are constantly detected by VirusTotal.
